### ISSUE TITLE
Missing transliteration for 'đ'

### ISSUE THREAD

**Issue by BilalSehovic** [mnicic/serbian-transliterator#1]
Library is missing transliteration for letter 'đ'. 
After having look through the source code I can see that transliteration for 'đ' is reserved for 'dj'.
This should either be replaced or transliteration for 'đ' can be added.

Other than that, library works great! :)

Best regards,
Bilal.

**Comment by mnicic** [comment]
Thank you! :)
Just published new version with the fix.
